words = [
	"agpl",
	"biomejs",
	"clicolor",
	"clippy",
	"codesearch",
	"dfs",
	"exa",
	"extglob",
	"extglobs",
	"globset",
	"jscpd",
	"keybind",
	"keybinds",
	"lossy",
	"matchers",
	"mcp",
	"openai",
	"opencode",
	"oxfmt",
	"pullhook",
	"rustflags",
	"sed",
	"thiserror",
	"todoread",
	"todowrite",
	"upstash",
	"uvx",
	"wakatime",
	"webfetch",
	"websearch",
	"zigbuild",
	"oxlint",
]
dictionaries = ["en_us"]
ignore_paths = []
use_global = true
