// oxlint-disable small-rules/prevent-abbreviations
export const MESSAGE_ID_REPLACE = "replace";
export const MESSAGE_ID_SUGGESTION = "suggestion";
export const ANOTHER_NAME_MESSAGE = "A more descriptive name will do too.";

export const DEFAULT_SHORTHANDS: Record<string, string> = {
	args: "parameters",
	char: "character",
	dt: "deltaTime",
	plr: "player",
};

export const DEFAULT_ALLOW_PROPERTY_ACCESS = ["char"];

export const DEFAULT_REPLACEMENTS: Record<string, Record<string, boolean>> = {
	acc: { accumulator: true },
	arg: { argument: true },
	args: { arguments: true },
	arr: { array: true },
	attr: { attribute: true },
	attrs: { attributes: true },
	btn: { button: true },
	cb: { callback: true },
	char: { character: true },
	conf: { config: true },
	ctx: { context: true },
	cur: { current: true },
	curr: { current: true },
	db: { database: true },
	def: { defer: true, deferred: true, define: true, definition: true },
	dest: { destination: true },
	dev: { development: true },
	dir: { direction: true, directory: true },
	dirs: { directories: true },
	dist: { distance: true },
	doc: { document: true },
	docs: { documentation: true, documents: true },
	dst: { daylightSavingTime: true, destination: true, distribution: true },
	dt: { dateTime: true, deltaTime: true },
	// oxlint-disable-next-line id-length
	e: { error: true, event: true },
	el: { element: true },
	elem: { element: true },
	elems: { elements: true },
	env: { environment: true },
	envs: { environments: true },
	err: { error: true },
	ev: { event: true },
	evt: { event: true },
	ext: { extension: true },
	exts: { extensions: true },
	fn: { func: true, function: true },
	func: { function: true },
	// oxlint-disable-next-line id-length
	i: { index: true },
	idx: { index: true },
	impl: { implementation: true },
	// oxlint-disable-next-line id-length
	j: { index: true },
	len: { length: true },
	lib: { library: true },
	mod: { module: true },
	msg: { message: true },
	num: { number: true },
	obj: { object: true },
	opts: { options: true },
	param: { parameter: true },
	params: { parameters: true },
	pkg: { package: true },
	plr: { player: true },
	prev: { previous: true },
	prod: { production: true },
	prop: { property: true },
	props: { properties: true },
	rel: { related: true, relationship: true, relative: true },
	req: { request: true },
	res: { resource: true, response: true, result: true },
	ret: { returnValue: true },
	retval: { returnValue: true },
	sep: { separator: true },
	src: { source: true },
	stdDev: { standardDeviation: true },
	str: { string: true },
	tbl: { table: true },
	temp: { temporary: true },
	tit: { title: true },
	tmp: { temporary: true },
	util: { utility: true },
	utils: { utilities: true },
	val: { value: true },
	var: { variable: true },
	vars: { variables: true },
	ver: { version: true },
};

export const DEFAULT_ALLOW_LIST: Record<string, boolean> = {
	defaultProps: true,
	devDependencies: true,
	EmberENV: true,
	getDerivedStateFromProps: true,
	getInitialProps: true,
	getServerSideProps: true,
	getStaticProps: true,
	iOS: true,
	obj: true,
	propTypes: true,
	setupFilesAfterEnv: true,
};

export const DEFAULT_IGNORE = ["i18n", "l10n"];

export const WORD_SPLIT_PATTERN = /(?=[A-Z])|(?<=[_.-])/u;

export const TYPESCRIPT_RESERVED_WORDS = new Set([
	"any",
	"as",
	"boolean",
	"break",
	"case",
	"catch",
	"class",
	"const",
	"constructor",
	"continue",
	"debugger",
	"declare",
	"default",
	"delete",
	"do",
	"else",
	"enum",
	"export",
	"extends",
	"false",
	"finally",
	"for",
	"from",
	"function",
	"get",
	"if",
	"implements",
	"import",
	"in",
	"instanceof",
	"interface",
	"let",
	"module",
	"new",
	"null",
	"number",
	"of",
	"package",
	"private",
	"protected",
	"public",
	"require",
	"return",
	"set",
	"static",
	"string",
	"super",
	"switch",
	"symbol",
	"this",
	"throw",
	"true",
	"try",
	"type",
	"typeof",
	"var",
	"void",
	"while",
	"with",
	"yield",
]);

export const IS_ALPHABETIC = /^[A-Za-z]+$/u;
